# Generated by Django 5.0.10 on 2025-01-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.ImageField(default='media/bio/bia_default.jpg', upload_to='media/bio/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/avater/avt_default.jpg', upload_to='media/avatar/'),
        ),
    ]
