# Generated by Django 5.0.10 on 2025-01-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_bio_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.ImageField(default='bio/bia_default.jpg', upload_to='bio/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='avater/avt_default.jpg', upload_to='avatar/'),
        ),
    ]
